# Node.js with React
- task: SonarQubePrepare@4
- task: SonarQubeAnalyze@4
  inputs:
    SonarQube: 'TimeTableManage'
    scannerMode: 'MSBuild'
    projectKey: '6033fb5331084abf1e72944f9cbfc2d9627e7fb9'
    projectName: 'TimeTable'
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
- task: SonarQubeAnalyze@4
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
